### ISSUE TITLE
pw-top tab empty

### ISSUE THREAD

**Issue by fabioraitz** [magillos/Cable#5]
pw-top tab is empty un linux mint 22.1 using flatpak

**Comment by magillos** [comment]
I only tested .deb package on Debian 12 in VM. It worked but it took some time to load that tab, for some reason. Can you run "pw-top -b" in terminal and see if the command is showing output?

**Comment by fabioraitz** [comment]
pw-top is working fine on terminal.

**Comment by magillos** [comment]
Have you tried deb, appimage, pyinstaller package (all in releases) or running the app as python script (instructions on the main page)? I would have to narrow it down and find out if it's flatpak issue and some missing args or something more broad.

**Comment by magillos** [comment]
AppImage may not work because you are on quite old distro (old glibc version).  This won't be fixed as I can't maintain that many packages. It's tedious enough with binaries I already supply. 
As of error with deb package; is your Pipewire at version 1.0 at least? With anything older than that, some things may work, some won't. Do you have pipewire-jack installed? I suspect it's the latter. (I'll add it as dependency to the deb package).

I was able to reproduce your flatpak issue and it was also present with deb package intermittently as well as with bare python script. I think I've fixed it but I need to do more testing before pushing an update.

**Comment by fabioraitz** [comment]
Linux mint 22.1 is based on Ubuntu 24.04 LTS, not even a year old, and mint 22.1 is less than 2 months old, not "quite old".

Pipewire version is 1.0.5. I installed pipewire-jack and the issues still the same.

**Comment by fabioraitz** [comment]
I dont have any jack specific stuff (jackd etc) only those tools proveded by pipewire, like pipewire-jack. Could be some permissions for flatpak?

**Comment by magillos** [comment]
I was referring to your error with deb. As you run Mint, it would be best if deb package worked for you. 
Flatpak is different story. I missed that it needs to run pw-top with flatpak-spawn, the same way the main app does with everything. But not too worry, I just might have it sorted: https://github.com/magillos/Cable/releases/download/0.6.1/Cable-0.6.1.flatpak

**Comment by fabioraitz** [comment]
Can confirm that pw-top is now working the flatpak version 0.6.1

**Comment by magillos** [comment]
Great. Can you tell me how fast is it refreshing? Every second or more like 5-6 seconds? I was testing it in VM and it was much slower than it would be on normal machine.

**Comment by fabioraitz** [comment]
each 5 seconds consistently

**Comment by magillos** [comment]
I guess it's not too bad and sufficient for what it is, and it's at least fixed.
